# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         File-Repl
version:      1.29
version_from: Repl.pm
installdirs:  site
requires:
    Carp:                          0
    File::Basename:                0
    File::Copy:                    0
    File::Find:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
