---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.64, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: File-Repl
no_index:
  directory:
    - t
    - inc
requires:
  File::Basename: 2.6
  File::Copy: 2.03
  File::Find: 0
  Win32::API: 0
  Win32::AdminMisc: 0
version: 1.31
